name: publish package

on:
  push:

jobs:
  test:
    name: release npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - name: test
        run: npm run test
